# Generated by Django 4.0.6 on 2024-01-28 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_visit_remove_blogcomment_author_blog_views_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visit',
        ),
    ]
