# Generated by Django 4.0.6 on 2024-02-13 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_blogcomment_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='name',
        ),
    ]
